name = "rhythm-editor"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "rhythm-editor"
database_id = "a9a0a0d2-1db7-41d5-8232-1ae26d1b9e82"
