name = "rhythm-studio"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "rhythm-studio"
database_id = "ad32a4a5-fdbe-46a6-abd9-89fb00a82287"
